use std::error::Error;

mod day_one;

fn main() -> Result<(), Box<dyn Error>> {
    day_one::run()
}
